### ISSUE TITLE
Issue with \IfFormatAtLeastF.

### ISSUE THREAD

**Issue by denniswo** [FrankMittelbach/fmitex-footmisc#20]
After an update of footmisc (from 6.0g to 7.0a), this packages causes a compilation error for me.

The new version of **footmisc.sty** uses the command `\IfFormatAtLeastF{<format>}{<code>}`.
Changing this line to `\IfFormatAtLeastTF{<format>}{}{<code>}` appears to solve the issue.

Looking at the **ltclass** file, I see that the single-branch commands are also defined:
```
\def\IfFormatAtLeastT   #1#2{\IfFormatAtLeastTF{#1}{#2}{}}
\def\IfFormatAtLeastF     #1{\IfFormatAtLeastTF{#1}{}}
```

However, I would've expected the latter to be:
`\def\IfFormatAtLeastF   #1#2{\IfFormatAtLeastTF{#1}{}{#2}}`

The compilation error is:
```
! Undefined control sequence.
l.52 \IfFormatAtLeastF
{2025-06-01}{\input{footmisc-2022-02-14.sty}\endinput}
```

**Comment by FrankMittelbach** [comment]
Looks like a stupid mistake. Unfortunately I can't do any fixes right now. So this has to wait until mid May.

**Comment by u-fischer** [comment]
Can you please show a small but complete example and the log-file?

Your error message looks as if you are trying to use the new footmisc in an older TeX system, I e.g. get this if I use it in a texlive 2023. 

The definition in LaTeX looks fine, `\IfFormatAtLeastF{date}{code}` will expand to `\IfFormatAtLeastTF{date}{}{code}` and that is what you want.

**Comment by denniswo** [comment]
Ulrike was right; this appears to have been causes by an incomplete update. Closing the issue.

I prepared a minimal example, but could not reproduce the issue on my (up-to-date) system. Going back to the original system (on which the issue was encountered), this example did fail. Comparing the logs, I found a difference in LaTeX version:

My system:
```
LaTeX2e <2024-11-01> patch level 2
L3 programming layer <2025-01-18>
```
Original system:
```
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-04>
```

After updating the original system (again), the issue disappeared.

**Comment by FrankMittelbach** [comment]
The idea was that the code should work with an older format, so I change to use `\IfFormatAtLeastTF` because that is available for a while.
